# Adaptable irrigation strategies 
## soil moisture targets

Previous work has examined the benifits of choosing the optimal irrigation stratgy for farm profits and water use efficiency.

Though as the season unfolds, farmers may want to adjust their irrigation strategy based on the climate conditions so far and their expectation of the weather for the rest of the season.


In [1]:
# !pip install aquacrop

In [1]:
from aquacrop.classes import *
from aquacrop.core import *
from aquacrop.lars import *

from scipy.optimize import differential_evolution
import numpy as np
from functools import partial
import pandas as pd
import matplotlib.pyplot as plt

In [14]:
from aquacropgym.envs import CropEnv, nebraska_maize_config, cordoba_cotton_config,california_tomato_config
from aquacropgym.utils import evaluate_agent,evaluate_agent_single_year
from aquacropgym.utils import calc_eto_faopm,get_mean_std


In [3]:
class FixedThresholdAgent():
    def __init__(self,smts):
        self.smts=smts # gievn as fraction

    
    def compute_action(self,obs):
        "default observation set"

        return (self.smts*2)-1

## Champion - Maize

In [4]:
max_bound = np.ones(4)
min_bound = np.zeros(4)
bounds = [(min_bound[i], max_bound[i]) for i in range(4)]


In [10]:

#CP  Lat.(deg)= 40.40  Long.(deg)=101.73  Elev.(m)=1072. 

gendf_neb=calc_eto_faopm('data/CPWG.dat',1995,40.4,1072,True,["simyear","jday","minTemp","maxTemp","precip","rad"])
gendf_cal= calc_eto_faopm('data/CLWG.dat',1995,37.49,14.0,True,["simyear","jday","minTemp","maxTemp","precip","rad"])


In [11]:
for iplace,gendf in enumerate([gendf_neb,gendf_cal]):
    print(iplace)

    test_env_config=[nebraska_maize_config,california_tomato_config][iplace].copy()

    for icrop,crop in enumerate(['Maize','Sorghum','Wheat','Tomato','Soybean']):

        crop_prices=[180,180,312,82,444]
        # test_env_config=nebraska_maize_config.copy()

        test_env_config['gendf']=gendf
        test_env_config['evaluation_run']=True
        test_env_config['normalize_obs']=False
        test_env_config['action_set']='smt4'
        test_env_config['observation_set']='default'
        test_env_config['days_to_irr']=3
        test_env_config['crop']=CropClass(crop,PlantingDate='05/01',)
        test_env_config['crop_price']=crop_prices[icrop]
        test_env_config['fixed_cost']=0.
        print(crop)
        print(evaluate_agent(FixedThresholdAgent(np.array([0.7]*4)),CropEnv,test_env_config))

        res = differential_evolution(optim_func,bounds=bounds,workers=8,disp=True,seed=43,tol=0.001,popsize=5)
        print(evaluate_agent(FixedThresholdAgent(res.x),CropEnv,test_env_config))
        print(res.x)

0
Maize
(2010.3254644178012, 2016.4700266576485)


/home/mbyx3tk2/.local/lib/python3.8/site-packages/scipy/optimize/_differentialevolution.py:492: UserWarning: differential_evolution: the 'workers' keyword has overridden updating='immediate' to updating='deferred'
  warnings.warn("differential_evolution: the 'workers' keyword has"


differential_evolution step 1: f(x)= -2190.87
differential_evolution step 2: f(x)= -2192.98
differential_evolution step 3: f(x)= -2218.27
differential_evolution step 4: f(x)= -2231.3
differential_evolution step 5: f(x)= -2231.3
differential_evolution step 6: f(x)= -2231.3
differential_evolution step 7: f(x)= -2233.44
differential_evolution step 8: f(x)= -2244.32
differential_evolution step 9: f(x)= -2244.32
differential_evolution step 10: f(x)= -2244.32
differential_evolution step 11: f(x)= -2244.32
differential_evolution step 12: f(x)= -2244.32
differential_evolution step 13: f(x)= -2244.32
differential_evolution step 14: f(x)= -2244.32
differential_evolution step 15: f(x)= -2244.32
differential_evolution step 16: f(x)= -2244.32
differential_evolution step 17: f(x)= -2244.32
differential_evolution step 18: f(x)= -2244.32
(2244.3160234280404, 2249.6462754273703)
[0.68250447 0.6045603  0.34735624 0.1599799 ]
Sorghum
(1212.875586753849, 1222.6191493344138)


/home/mbyx3tk2/.local/lib/python3.8/site-packages/scipy/optimize/_differentialevolution.py:492: UserWarning: differential_evolution: the 'workers' keyword has overridden updating='immediate' to updating='deferred'
  warnings.warn("differential_evolution: the 'workers' keyword has"


differential_evolution step 1: f(x)= -1541.17
differential_evolution step 2: f(x)= -1547.22
differential_evolution step 3: f(x)= -1597.67
differential_evolution step 4: f(x)= -1597.67
differential_evolution step 5: f(x)= -1597.67
differential_evolution step 6: f(x)= -1608.32
differential_evolution step 7: f(x)= -1608.32
differential_evolution step 8: f(x)= -1608.41
differential_evolution step 9: f(x)= -1611.03
differential_evolution step 10: f(x)= -1614.94
differential_evolution step 11: f(x)= -1620.33
differential_evolution step 12: f(x)= -1620.39
differential_evolution step 13: f(x)= -1632.59
differential_evolution step 14: f(x)= -1634.97
differential_evolution step 15: f(x)= -1634.97
differential_evolution step 16: f(x)= -1640.99
differential_evolution step 17: f(x)= -1641.07
differential_evolution step 18: f(x)= -1643.11
differential_evolution step 19: f(x)= -1646.54
differential_evolution step 20: f(x)= -1646.54
differential_evolution step 21: f(x)= -1648.19
differential_evolution

/home/mbyx3tk2/.local/lib/python3.8/site-packages/scipy/optimize/_differentialevolution.py:492: UserWarning: differential_evolution: the 'workers' keyword has overridden updating='immediate' to updating='deferred'
  warnings.warn("differential_evolution: the 'workers' keyword has"


differential_evolution step 1: f(x)= -2427.99
differential_evolution step 2: f(x)= -2427.99
differential_evolution step 3: f(x)= -2427.99
differential_evolution step 4: f(x)= -2427.99
differential_evolution step 5: f(x)= -2430.02
differential_evolution step 6: f(x)= -2430.02
differential_evolution step 7: f(x)= -2434
differential_evolution step 8: f(x)= -2434
differential_evolution step 9: f(x)= -2434.87
differential_evolution step 10: f(x)= -2434.87
differential_evolution step 11: f(x)= -2439.44
differential_evolution step 12: f(x)= -2443.55
differential_evolution step 13: f(x)= -2443.55
differential_evolution step 14: f(x)= -2443.55
differential_evolution step 15: f(x)= -2443.55
differential_evolution step 16: f(x)= -2443.55
differential_evolution step 17: f(x)= -2443.55
differential_evolution step 18: f(x)= -2443.55
differential_evolution step 19: f(x)= -2443.55
differential_evolution step 20: f(x)= -2443.55
(2443.545378690777, 2440.3552296223133)
[0.07481395 0.43470723 0.38203116 0

/home/mbyx3tk2/.local/lib/python3.8/site-packages/scipy/optimize/_differentialevolution.py:492: UserWarning: differential_evolution: the 'workers' keyword has overridden updating='immediate' to updating='deferred'
  warnings.warn("differential_evolution: the 'workers' keyword has"


differential_evolution step 1: f(x)= -268.177
differential_evolution step 2: f(x)= -268.177
differential_evolution step 3: f(x)= -269.834
differential_evolution step 4: f(x)= -281.888
differential_evolution step 5: f(x)= -294.665
differential_evolution step 6: f(x)= -294.665
differential_evolution step 7: f(x)= -303.783
differential_evolution step 8: f(x)= -307.884
differential_evolution step 9: f(x)= -310.124
differential_evolution step 10: f(x)= -310.38
differential_evolution step 11: f(x)= -310.38
differential_evolution step 12: f(x)= -310.478
differential_evolution step 13: f(x)= -310.759
differential_evolution step 14: f(x)= -310.931
differential_evolution step 15: f(x)= -310.931
differential_evolution step 16: f(x)= -311.566
differential_evolution step 17: f(x)= -311.956
differential_evolution step 18: f(x)= -311.956
differential_evolution step 19: f(x)= -311.956
differential_evolution step 20: f(x)= -312.099
differential_evolution step 21: f(x)= -312.099
differential_evolution s

/home/mbyx3tk2/.local/lib/python3.8/site-packages/scipy/optimize/_differentialevolution.py:492: UserWarning: differential_evolution: the 'workers' keyword has overridden updating='immediate' to updating='deferred'
  warnings.warn("differential_evolution: the 'workers' keyword has"


differential_evolution step 1: f(x)= -1585.41
differential_evolution step 2: f(x)= -1585.41
differential_evolution step 3: f(x)= -1596.87
differential_evolution step 4: f(x)= -1600.82
differential_evolution step 5: f(x)= -1612.6
differential_evolution step 6: f(x)= -1616.12
differential_evolution step 7: f(x)= -1616.12
differential_evolution step 8: f(x)= -1624.51
differential_evolution step 9: f(x)= -1624.51
differential_evolution step 10: f(x)= -1624.51
differential_evolution step 11: f(x)= -1624.51
differential_evolution step 12: f(x)= -1624.51
differential_evolution step 13: f(x)= -1625.51
differential_evolution step 14: f(x)= -1625.51
differential_evolution step 15: f(x)= -1626.92
differential_evolution step 16: f(x)= -1627.29
differential_evolution step 17: f(x)= -1627.65
differential_evolution step 18: f(x)= -1627.65
differential_evolution step 19: f(x)= -1627.65
differential_evolution step 20: f(x)= -1627.65
(1627.6458117482996, 1637.605346473003)
[0.61640904 0.6270773  0.47817

/home/mbyx3tk2/.local/lib/python3.8/site-packages/scipy/optimize/_differentialevolution.py:492: UserWarning: differential_evolution: the 'workers' keyword has overridden updating='immediate' to updating='deferred'
  warnings.warn("differential_evolution: the 'workers' keyword has"


differential_evolution step 1: f(x)= -2249.47
differential_evolution step 2: f(x)= -2259.27
differential_evolution step 3: f(x)= -2279.46
differential_evolution step 4: f(x)= -2279.46
differential_evolution step 5: f(x)= -2279.46
differential_evolution step 6: f(x)= -2279.46
differential_evolution step 7: f(x)= -2279.46
differential_evolution step 8: f(x)= -2279.46
differential_evolution step 9: f(x)= -2279.46
differential_evolution step 10: f(x)= -2279.97
differential_evolution step 11: f(x)= -2279.97
differential_evolution step 12: f(x)= -2280
differential_evolution step 13: f(x)= -2280
differential_evolution step 14: f(x)= -2280
(2279.99717986057, 2278.131697439546)
[0.76145598 0.69618318 0.45328821 0.13657128]
Sorghum
(1332.6977265279986, 1332.4477095822997)


/home/mbyx3tk2/.local/lib/python3.8/site-packages/scipy/optimize/_differentialevolution.py:492: UserWarning: differential_evolution: the 'workers' keyword has overridden updating='immediate' to updating='deferred'
  warnings.warn("differential_evolution: the 'workers' keyword has"


differential_evolution step 1: f(x)= -1583.25
differential_evolution step 2: f(x)= -1583.25
differential_evolution step 3: f(x)= -1621.59
differential_evolution step 4: f(x)= -1662.27
differential_evolution step 5: f(x)= -1662.27
differential_evolution step 6: f(x)= -1662.27
differential_evolution step 7: f(x)= -1662.27
differential_evolution step 8: f(x)= -1662.27
differential_evolution step 9: f(x)= -1662.27
differential_evolution step 10: f(x)= -1673.95
differential_evolution step 11: f(x)= -1673.95
differential_evolution step 12: f(x)= -1673.95
differential_evolution step 13: f(x)= -1676.03
differential_evolution step 14: f(x)= -1678.26
differential_evolution step 15: f(x)= -1678.26
differential_evolution step 16: f(x)= -1678.26
differential_evolution step 17: f(x)= -1679.19
differential_evolution step 18: f(x)= -1679.19
differential_evolution step 19: f(x)= -1679.19
(1679.1891698972172, 1672.1369189066868)
[0.59470297 0.65310174 0.27643592 0.26878403]
Wheat
(2688.03684092127, 2686

/home/mbyx3tk2/.local/lib/python3.8/site-packages/scipy/optimize/_differentialevolution.py:492: UserWarning: differential_evolution: the 'workers' keyword has overridden updating='immediate' to updating='deferred'
  warnings.warn("differential_evolution: the 'workers' keyword has"


differential_evolution step 1: f(x)= -2742.98
differential_evolution step 2: f(x)= -2742.98
differential_evolution step 3: f(x)= -2742.98
differential_evolution step 4: f(x)= -2742.98
differential_evolution step 5: f(x)= -2742.98
differential_evolution step 6: f(x)= -2743.41
differential_evolution step 7: f(x)= -2751.4
differential_evolution step 8: f(x)= -2751.4
differential_evolution step 9: f(x)= -2751.4
differential_evolution step 10: f(x)= -2751.4
differential_evolution step 11: f(x)= -2752.39
differential_evolution step 12: f(x)= -2752.39
differential_evolution step 13: f(x)= -2753.3
(2753.3010271417807, 2751.5801864968557)
[0.54715451 0.71245115 0.3639099  0.32017787]
Tomato
(285.72935314230637, 283.4379035871694)


/home/mbyx3tk2/.local/lib/python3.8/site-packages/scipy/optimize/_differentialevolution.py:492: UserWarning: differential_evolution: the 'workers' keyword has overridden updating='immediate' to updating='deferred'
  warnings.warn("differential_evolution: the 'workers' keyword has"


differential_evolution step 1: f(x)= -297.836
differential_evolution step 2: f(x)= -324.21
differential_evolution step 3: f(x)= -324.21
differential_evolution step 4: f(x)= -324.226
differential_evolution step 5: f(x)= -324.978
differential_evolution step 6: f(x)= -325.363
differential_evolution step 7: f(x)= -325.57
differential_evolution step 8: f(x)= -325.97
differential_evolution step 9: f(x)= -325.97
differential_evolution step 10: f(x)= -325.97
differential_evolution step 11: f(x)= -326.068
differential_evolution step 12: f(x)= -326.068
differential_evolution step 13: f(x)= -326.261
differential_evolution step 14: f(x)= -326.261
differential_evolution step 15: f(x)= -326.261
differential_evolution step 16: f(x)= -326.342
differential_evolution step 17: f(x)= -326.652
differential_evolution step 18: f(x)= -326.652
differential_evolution step 19: f(x)= -326.652
differential_evolution step 20: f(x)= -326.652
differential_evolution step 21: f(x)= -326.816
differential_evolution step 

/home/mbyx3tk2/.local/lib/python3.8/site-packages/scipy/optimize/_differentialevolution.py:492: UserWarning: differential_evolution: the 'workers' keyword has overridden updating='immediate' to updating='deferred'
  warnings.warn("differential_evolution: the 'workers' keyword has"


differential_evolution step 1: f(x)= -1630.69
differential_evolution step 2: f(x)= -1643.2
differential_evolution step 3: f(x)= -1643.2
differential_evolution step 4: f(x)= -1644.01
differential_evolution step 5: f(x)= -1644.01
differential_evolution step 6: f(x)= -1648.26
differential_evolution step 7: f(x)= -1651.93
differential_evolution step 8: f(x)= -1651.93
differential_evolution step 9: f(x)= -1651.93
differential_evolution step 10: f(x)= -1654.75
differential_evolution step 11: f(x)= -1655.9
differential_evolution step 12: f(x)= -1655.9
differential_evolution step 13: f(x)= -1657.16
differential_evolution step 14: f(x)= -1657.16
differential_evolution step 15: f(x)= -1657.16
differential_evolution step 16: f(x)= -1657.16
(1657.161333687051, 1654.8568911323173)
[0.63187864 0.64375322 0.79073555 0.29191425]


In [11]:
test_env_config=nebraska_maize_config.copy()

test_env_config['gendf']=gendf
test_env_config['evaluation_run']=True
test_env_config['normalize_obs']=False
# test_env_config['include_rain']=False
test_env_config['action_set']='smt4'
test_env_config['observation_set']='default'
test_env_config['days_to_irr']=3
# test_env_config['crop']='Cotton'
# test_env_config['crop_price']=366.
# test_env_config['soil']='ClayLoam'



In [10]:
gendf=calc_eto_faopm('data/CPWG.dat',1995,40.4,1072,True,["simyear","jday","minTemp","maxTemp","precip","rad"])


In [12]:
evaluate_agent(FixedThresholdAgent(np.array([0.69892958, 0.56825608, 0.35286359, 0.11124398])),CropEnv,test_env_config)

(513.0584847087756, 521.3771423907657)

In [15]:
get_mean_std(np.array([0.69892958, 0.56825608, 0.35286359, 0.11124398]),CropEnv,test_env_config)

513.0584847087756
(3080, 24)


(array([1.5068182e+01, 6.7727275e+00, 4.4094244e-01, 6.8477272e+01,
        1.2823775e+02, 6.5737528e-01, 1.2552679e+03, 2.2174017e+00,
        5.9947405e+00, 1.6800790e+02, 4.0232184e+02, 2.2348366e+00,
        6.0216384e+00, 1.7755436e+00, 1.8451277e+00, 1.3106525e+00,
        1.7755436e+00, 1.8451277e+00, 1.3106525e+00, 1.7755436e+00,
        1.8181819e-01, 2.0454545e-01, 4.0909091e-01, 2.0454545e-01],
       dtype=float32),
 array([8.8430672e+00, 1.2588633e+00, 2.1731496e-01, 3.8057072e+01,
        8.1543999e+01, 3.7534222e-01, 1.0305146e+03, 2.6845067e+00,
        9.4314069e-01, 1.0874526e+02, 2.4056461e+02, 6.7858462e+00,
        1.6485872e+00, 6.4046011e+00, 6.5145025e+00, 5.5642538e+00,
        6.4046006e+00, 6.5145020e+00, 5.5642538e+00, 6.4046006e+00,
        3.8569000e-01, 4.0337056e-01, 4.9166963e-01, 4.0337056e-01],
       dtype=float32))

In [5]:
def optim_func(smt):
    train,test = evaluate_agent(FixedThresholdAgent(smt.reshape(-1)),CropEnv,test_env_config)
    
    return -train

In [18]:
max_bound = np.ones(4)
min_bound = np.zeros(4)
bounds = [(min_bound[i], max_bound[i]) for i in range(4)]

# res = differential_evolution(optim_func,bounds=bounds,disp=True,workers=8,seed=43,tol=0.001,popsize=5)

differential_evolution step 1: f(x)= -462.874
differential_evolution step 2: f(x)= -464.981
differential_evolution step 3: f(x)= -490.274
differential_evolution step 4: f(x)= -503.302
differential_evolution step 5: f(x)= -503.302
differential_evolution step 6: f(x)= -503.302
differential_evolution step 7: f(x)= -505.438
differential_evolution step 8: f(x)= -516.316
differential_evolution step 9: f(x)= -516.316
differential_evolution step 10: f(x)= -516.316
differential_evolution step 11: f(x)= -516.316
differential_evolution step 12: f(x)= -516.316
differential_evolution step 13: f(x)= -516.316
differential_evolution step 14: f(x)= -516.316
differential_evolution step 15: f(x)= -516.316
differential_evolution step 16: f(x)= -516.316
differential_evolution step 17: f(x)= -516.316
differential_evolution step 18: f(x)= -516.316
differential_evolution step 19: f(x)= -516.316
differential_evolution step 20: f(x)= -516.316
differential_evolution step 21: f(x)= -516.403
differential_evolution

In [19]:
res

     fun: -516.4032300997322
 message: 'Optimization terminated successfully.'
    nfev: 585
     nit: 28
 success: True
       x: array([0.68282431, 0.56990258, 0.34908719, 0.13661482])

In [20]:
evaluate_agent(FixedThresholdAgent(res.x),CropEnv,test_env_config)

(516.4032300997322, 523.4126548993457)

single year

In [21]:
def optim_func_single_year(smt,sim_year=1):
    prof = evaluate_agent_single_year(FixedThresholdAgent(smt.reshape(-1)),CropEnv,test_env_config,sim_year=sim_year)
    
    return -prof

max_bound = np.ones(4)
min_bound = np.zeros(4)
bounds = [(min_bound[i], max_bound[i]) for i in range(4)]



In [22]:
from functools import partial

In [23]:
optim_func_single_year(np.array([0.7]*4))

-259.0132100582682

In [28]:
years=[]
smts=[]
profs=[]
for y in range(1,101):
    func = partial(optim_func_single_year,sim_year=y)
    res = differential_evolution(optim_func,bounds=bounds,disp=True,workers=8,seed=43,tol=0.1,popsize=8)
    # res = differential_evolution(func,bounds=bounds,disp=True,workers=8,seed=43)
    p = evaluate_agent_single_year(FixedThresholdAgent(res.x.reshape(-1)),CropEnv,test_env_config,y)
    years.append(y)
    smts.append(res.x)
    profs.append(p)
    result_df = pd.DataFrame([years,smts,profs]).T

    result_df.to_csv('potential/champion_optim_smt_results.csv')

differential_evolution step 1: f(x)= -474.174
differential_evolution step 2: f(x)= -477.361
differential_evolution step 3: f(x)= -490.546


/home/mbyx3tk2/.local/lib/python3.8/site-packages/scipy/optimize/_differentialevolution.py:492: UserWarning: differential_evolution: the 'workers' keyword has overridden updating='immediate' to updating='deferred'
  warnings.warn("differential_evolution: the 'workers' keyword has"


differential_evolution step 1: f(x)= -474.174
differential_evolution step 2: f(x)= -477.361
differential_evolution step 3: f(x)= -490.546


/home/mbyx3tk2/.local/lib/python3.8/site-packages/scipy/optimize/_differentialevolution.py:492: UserWarning: differential_evolution: the 'workers' keyword has overridden updating='immediate' to updating='deferred'
  warnings.warn("differential_evolution: the 'workers' keyword has"


differential_evolution step 1: f(x)= -474.174
differential_evolution step 2: f(x)= -477.361
differential_evolution step 3: f(x)= -490.546


/home/mbyx3tk2/.local/lib/python3.8/site-packages/scipy/optimize/_differentialevolution.py:492: UserWarning: differential_evolution: the 'workers' keyword has overridden updating='immediate' to updating='deferred'
  warnings.warn("differential_evolution: the 'workers' keyword has"


differential_evolution step 1: f(x)= -474.174
differential_evolution step 2: f(x)= -477.361
differential_evolution step 3: f(x)= -490.546


/home/mbyx3tk2/.local/lib/python3.8/site-packages/scipy/optimize/_differentialevolution.py:492: UserWarning: differential_evolution: the 'workers' keyword has overridden updating='immediate' to updating='deferred'
  warnings.warn("differential_evolution: the 'workers' keyword has"


differential_evolution step 1: f(x)= -474.174
differential_evolution step 2: f(x)= -477.361
differential_evolution step 3: f(x)= -490.546


/home/mbyx3tk2/.local/lib/python3.8/site-packages/scipy/optimize/_differentialevolution.py:492: UserWarning: differential_evolution: the 'workers' keyword has overridden updating='immediate' to updating='deferred'
  warnings.warn("differential_evolution: the 'workers' keyword has"


differential_evolution step 1: f(x)= -474.174
differential_evolution step 2: f(x)= -477.361
differential_evolution step 3: f(x)= -490.546


/home/mbyx3tk2/.local/lib/python3.8/site-packages/scipy/optimize/_differentialevolution.py:492: UserWarning: differential_evolution: the 'workers' keyword has overridden updating='immediate' to updating='deferred'
  warnings.warn("differential_evolution: the 'workers' keyword has"


differential_evolution step 1: f(x)= -474.174
differential_evolution step 2: f(x)= -477.361
differential_evolution step 3: f(x)= -490.546


/home/mbyx3tk2/.local/lib/python3.8/site-packages/scipy/optimize/_differentialevolution.py:492: UserWarning: differential_evolution: the 'workers' keyword has overridden updating='immediate' to updating='deferred'
  warnings.warn("differential_evolution: the 'workers' keyword has"


differential_evolution step 1: f(x)= -474.174
differential_evolution step 2: f(x)= -477.361
differential_evolution step 3: f(x)= -490.546


/home/mbyx3tk2/.local/lib/python3.8/site-packages/scipy/optimize/_differentialevolution.py:492: UserWarning: differential_evolution: the 'workers' keyword has overridden updating='immediate' to updating='deferred'
  warnings.warn("differential_evolution: the 'workers' keyword has"


differential_evolution step 1: f(x)= -474.174
differential_evolution step 2: f(x)= -477.361
differential_evolution step 3: f(x)= -490.546


/home/mbyx3tk2/.local/lib/python3.8/site-packages/scipy/optimize/_differentialevolution.py:492: UserWarning: differential_evolution: the 'workers' keyword has overridden updating='immediate' to updating='deferred'
  warnings.warn("differential_evolution: the 'workers' keyword has"


differential_evolution step 1: f(x)= -474.174
differential_evolution step 2: f(x)= -477.361
differential_evolution step 3: f(x)= -490.546


/home/mbyx3tk2/.local/lib/python3.8/site-packages/scipy/optimize/_differentialevolution.py:492: UserWarning: differential_evolution: the 'workers' keyword has overridden updating='immediate' to updating='deferred'
  warnings.warn("differential_evolution: the 'workers' keyword has"
Process ForkPoolWorker-164:
Process ForkPoolWorker-168:
Process ForkPoolWorker-167:


KeyboardInterrupt: 

## cordoba - cotton

In [29]:
#cd 37.31, 110
gendf=calc_eto_faopm('data/CDWG.dat',1995,37.31,110,True,["simyear","jday","minTemp","maxTemp","precip","rad"])

In [30]:
test_env_config=cordoba_cotton_config.copy()

test_env_config['gendf']=gendf
test_env_config['evaluation_run']=True
test_env_config['normalize_obs']=False
test_env_config['action_set']='smt4'
test_env_config['observation_set']='default'
# test_env_config['include_rain']=False


In [31]:
evaluate_agent(FixedThresholdAgent(np.array([0.58709859, 0.66129679, 0.34608978, 0.10645481])),CropEnv,test_env_config)

(1409.5207135643152, 1413.5129547576225)

In [33]:
def optim_func(smt):
    train,test = evaluate_agent(FixedThresholdAgent(smt.reshape(-1)),CropEnv,test_env_config)
    
    return -train

In [34]:
max_bound = np.ones(4)
min_bound = np.zeros(4)
bounds = [(min_bound[i], max_bound[i]) for i in range(4)]

res = differential_evolution(optim_func,bounds=bounds,disp=True,workers=8,seed=43,tol=0.001,popsize=5)

/home/mbyx3tk2/.local/lib/python3.8/site-packages/scipy/optimize/_differentialevolution.py:492: UserWarning: differential_evolution: the 'workers' keyword has overridden updating='immediate' to updating='deferred'
  warnings.warn("differential_evolution: the 'workers' keyword has"


differential_evolution step 1: f(x)= -1416.47
differential_evolution step 2: f(x)= -1416.47
differential_evolution step 3: f(x)= -1432.22
differential_evolution step 4: f(x)= -1488.86
differential_evolution step 5: f(x)= -1495.41
differential_evolution step 6: f(x)= -1495.41
differential_evolution step 7: f(x)= -1495.41
differential_evolution step 8: f(x)= -1497.64
differential_evolution step 9: f(x)= -1501.82
differential_evolution step 10: f(x)= -1512.71
differential_evolution step 11: f(x)= -1512.71
differential_evolution step 12: f(x)= -1522.07
differential_evolution step 13: f(x)= -1522.07
differential_evolution step 14: f(x)= -1522.07
differential_evolution step 15: f(x)= -1522.07
differential_evolution step 16: f(x)= -1522.07
differential_evolution step 17: f(x)= -1522.07


In [35]:
res

     fun: -1522.0704563789905
 message: 'Optimization terminated successfully.'
    nfev: 365
     nit: 17
 success: True
       x: array([0.68270609, 0.37501385, 0.2554435 , 0.25134306])

In [36]:
evaluate_agent(FixedThresholdAgent(res.x),CropEnv,test_env_config)

(1522.0704563789905, 1524.7180609532068)

## California - Tomato

In [8]:

#CL  37.49	-121.07	14.00 
gendf= calc_eto_faopm('data/CLWG.dat',1995,37.49,14.0,True,["simyear","jday","minTemp","maxTemp","precip","rad"])


In [9]:
test_env_config=california_tomato_config.copy()

test_env_config['gendf']=gendf
test_env_config['evaluation_run']=True
test_env_config['normalize_obs']=False
# test_env_config['include_rain']=False
test_env_config['action_set']='smt4'
test_env_config['observation_set']='default'
# test_env_config['irrigation_cost']=1.
# test_env_config['crop']='MaizeChampionGDD'
# test_env_config['soil']='ClayLoam'

# test_env_config['crop']=CropClass('Tomato',PlantingDate='04/01',PlantPop=100_000,SeedSize=22,CCx=0.9)
test_env_config['crop']=CropClass('Maize',PlantingDate='05/01',)
test_env_config['planting_date']='05/01'
test_env_config['soil']='SandyLoam'
test_env_config['crop_price']=180
# test_env_config['CO2conc']=None

#     soil='Loam', # soil type (str or SoilClass)

# CO2conc=363.8,
# simcalyear=1995,

In [10]:
evaluate_agent(FixedThresholdAgent(np.array([1]*4)),CropEnv,test_env_config)

(2081.6076376996375, 2084.210268831199)

In [11]:
def optim_func(smt):
    train,test = evaluate_agent(FixedThresholdAgent(smt.reshape(-1)),CropEnv,test_env_config)
    
    return -train

max_bound = np.ones(4)
min_bound = np.zeros(4)
bounds = [(min_bound[i], max_bound[i]) for i in range(4)]

res = differential_evolution(optim_func,bounds=bounds,disp=True,workers=8,seed=43,tol=0.001,popsize=5)

/home/mbyx3tk2/.local/lib/python3.8/site-packages/scipy/optimize/_differentialevolution.py:492: UserWarning: differential_evolution: the 'workers' keyword has overridden updating='immediate' to updating='deferred'
  warnings.warn("differential_evolution: the 'workers' keyword has"


differential_evolution step 1: f(x)= -2242.02
differential_evolution step 2: f(x)= -2242.02
differential_evolution step 3: f(x)= -2247.43
differential_evolution step 4: f(x)= -2261.24
differential_evolution step 5: f(x)= -2261.24
differential_evolution step 6: f(x)= -2266.47
differential_evolution step 7: f(x)= -2266.47
differential_evolution step 8: f(x)= -2266.47
differential_evolution step 9: f(x)= -2269.94
differential_evolution step 10: f(x)= -2269.94
differential_evolution step 11: f(x)= -2269.94
differential_evolution step 12: f(x)= -2269.94
differential_evolution step 13: f(x)= -2269.94


KeyboardInterrupt: 

In [9]:
evaluate_agent(FixedThresholdAgent(res.x),CropEnv,test_env_config)

(319.338429459985, 317.8306846069444)

In [7]:
wdf=gendf[gendf.simyear==4].drop('simyear',axis=1)

In [8]:
def run_model(smts,max_irr_season,year1,year2):
    """
    funciton to run model and return results for given set of soil moisture targets
    """

    maize = CropClass('Tomato',PlantingDate='05/1') # define crop
    loam = SoilClass('Loam') # define soil
    init_wc = InitWCClass(wc_type='Pct',value=[70]) # define initial soil water conditions

    irrmngt = IrrMngtClass(IrrMethod=1,SMT=smts,MaxIrrSeason=max_irr_season) # define irrigation management

    # create and run model
    model = AquaCropModel(f'{year1}/05/1',f'{year2}/12/31',wdf,loam,maize,
                          IrrMngt=irrmngt,InitWC=init_wc)
    model.initialize()
    model.step(till_termination=True)
    return model.Outputs.Final

run_model([70]*4,10_000,1995,1995)

Season Crop Type Harvest Date (YYYY/MM/DD) Harvest Date (Step)  \
0      0    Tomato                1995-08-19                 109   

   Yield (tonne/ha)  Seasonal irrigation (mm)  
0          7.652106                756.363735

619.65

In [7]:
evaluate_agent(FixedThresholdAgent(np.array([0.69892958, 0.56825608, 0.35286359, 0.11124398])),CropEnv,test_env_config)

(270.9868053314722, 269.8517950217337)

In [8]:
evaluate_agent(FixedThresholdAgent(np.array([0.]*4)),CropEnv,test_env_config)

(4.046373497676493, 4.514327303782176)

In [9]:
def optim_func(smt):
    train,test = evaluate_agent(FixedThresholdAgent(smt.reshape(-1)),CropEnv,test_env_config)
    
    return -train

In [10]:
max_bound = np.ones(4)
min_bound = np.zeros(4)
bounds = [(min_bound[i], max_bound[i]) for i in range(4)]

res = differential_evolution(optim_func,bounds=bounds,disp=True,workers=8,seed=43)

/home/mbyx3tk2/.local/lib/python3.8/site-packages/scipy/optimize/_differentialevolution.py:492: UserWarning: differential_evolution: the 'workers' keyword has overridden updating='immediate' to updating='deferred'
  warnings.warn("differential_evolution: the 'workers' keyword has"


differential_evolution step 1: f(x)= -316.315
differential_evolution step 2: f(x)= -318.177
differential_evolution step 3: f(x)= -318.177
differential_evolution step 4: f(x)= -318.177
differential_evolution step 5: f(x)= -318.177
differential_evolution step 6: f(x)= -318.177
differential_evolution step 7: f(x)= -318.177
differential_evolution step 8: f(x)= -318.681
differential_evolution step 9: f(x)= -318.755


In [11]:
res

     fun: -318.7546385264889
 message: 'Optimization terminated successfully.'
    nfev: 605
     nit: 9
 success: True
       x: array([0.64511612, 0.65667727, 0.79650656, 0.04541987])

In [12]:
evaluate_agent(FixedThresholdAgent(res.x),CropEnv,test_env_config)

(318.7546385264889, 316.29092174163)

In [13]:
from aquacropgym.utils import get_mean_std

In [14]:
get_mean_std(res.x,CropEnv,test_env_config)

318.7546385264889
(1120, 15)


(array([1.52500000e+01, 6.50000000e+00, 3.15283656e-01, 6.03125000e+01,
        3.07615387e+02, 5.10523260e-01, 4.98117859e+02, 1.24298476e-01,
        6.86775160e+00, 1.21339521e+01, 4.01664978e+02, 1.87500000e-01,
        3.12500000e-01, 2.50000000e-01, 2.50000000e-01], dtype=float32),
 array([8.2120342e+00, 1.1180340e+00, 1.6626830e-01, 3.1970348e+01,
        2.0187964e+02, 2.8188160e-01, 4.2335272e+02, 5.5605030e-01,
        6.5448678e-01, 1.5673932e+01, 2.2597920e+02, 3.9031237e-01,
        4.6351239e-01, 4.3301269e-01, 4.3301269e-01], dtype=float32))